// Generated by Wrangler on Wed Aug 14 2024 14:14:22 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  WEBHONC: DurableObjectNamespace<import("./src/index").WebHonc>;
}
