// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	PRIVATE_KEY: string;
	PUBLIC_KEY: string;
	DB: D1Database;
}
