/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TesterImport } from './routes/tester'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TesterRoute = TesterImport.update({
  id: '/tester',
  path: '/tester',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tester': {
      id: '/tester'
      path: '/tester'
      fullPath: '/tester'
      preLoaderRoute: typeof TesterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tester': typeof TesterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tester': typeof TesterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tester': typeof TesterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tester'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tester'
  id: '__root__' | '/' | '/tester'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TesterRoute: typeof TesterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TesterRoute: TesterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tester"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tester": {
      "filePath": "tester.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
