// Generated by Wrangler on Mon Aug 12 2024 22:29:21 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  WEBHONC: DurableObjectNamespace<import("./src/index").WebHonc>;
}
