// Generated by Wrangler on Wed Jul 03 2024 22:23:02 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	WEBHONC: DurableObjectNamespace;
}
