// Generated by Wrangler on Fri Jul 26 2024 14:34:46 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	WEBHONC: DurableObjectNamespace;
}
