name: Build Studio v1

on:
  pull_request:
    branches: ["*"]
    paths:
      - "apps/studio/studio-api/**"
      - "apps/studio/studio-frontend/**"
  push:
    branches: ["main", "release-*"]
    paths:
      - "apps/studio/studio-api/**"
      - "apps/studio/studio-frontend/**"

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true

jobs:
  build_packages:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Build shared types
        run: pnpm build:types

      # Linting: we use global biome command
      # any extra commands should be added to the lint:ci script
      # in the package.json

      - name: Lint all workspaces (biome)
        run: biome ci .

      - name: Lint all workspaces (eslint or other linters)
        run: pnpm --recursive lint:ci

      - name: Typecheck all workspaces
        run: pnpm --recursive typecheck

      # Testing

      - name: Test Studio API
        run: pnpm --filter @fiberplane/studio test

      - name: Test Studio Frontend
        run: pnpm --filter @fiberplane/studio-frontend test

      # Building

      - name: Build api, frontend and client library
        run: |
          pnpm \
            --filter=@fiberplane/studio-frontend \
            --filter=@fiberplane/studio \
            build

      # Release a preview version

      - name: Copy the frontend files into the api
        run: cp -r ./apps/studio/studio-frontend/dist/* ./apps/studio/studio-api/dist

      - name: Publish a temporary preview version
        run: pnpx pkg-pr-new publish --pnpm "./apps/studio/studio-api" "./packages/client-library-otel"
